access_key_id: AKIAI44QH8DHBEXAMPLE
secret_access_key: je7MtGbClwBF/2Zp9Utk/h3yCo8nvbEXAMPLEKEY
bucket_name: my-sample-bucket
region: us-west-2
stopwords:
    - deck
    - porch
    - housing
    - house
    - backyard
    - yard
    - alleyway
    - road
    - street
    - town
    - brick
    - building
    - alley
    - aerial view
    - algae
    - apartment building
    - apartment
    - appliance
    - architecture
    - balcony
    - banister
    - bench
    - blossom
    - boardwalk
    - cable car
    - chair
    - city
    - crypt
    - dog house
    - downtown
    - dungeon
    - field
    - flora
    - flower
    - freeway
    - furniture
    - grass
    - grassland
    - gutter
    - handrail
    - herbal
    - herbs
    - high rise
    - indoors
    - interior design
    - kennel
    - landslide
    - mobile home
    - moss
    - neighborhood
    - oven
    - path
    - phone
    - plant
    - planter
    - pool
    - potted plant
    - railing
    - ramp
    - room
    - screen
    - sidewalk
    - siding
    - soil
    - staircase
    - trail
    - trolley
    - urban
    - vehicle
    - villa
    - walkway
    - water
    - window
